### ISSUE TITLE
Write Jupyter notebook for the tensorwaves workflow

### ISSUE THREAD

**Issue by redeboer** [ComPWA/tensorwaves#62]
The [`examples/python/workflow.py`](https://github.com/ComPWA/tensorwaves/blob/master/examples/python/workflow.py) script already illustrates a complete fit procedure with tensorwaves, but needs to be rewritten into a Jupyter notebook. These notebooks should reflect the [ComPWA Workflow](https://compwa.github.io/usage/workflow). Step 2 of that workflow (generate data) is already as available in tensorwaves (see [`examples/jupyter/generate.ipynb`](https://github.com/ComPWA/tensorwaves/blob/master/examples/jupyter/generate.ipynb)).

- [x] [Step 1: Create amplitude model](https://compwa.github.io/usage/workflow/1_create_model.html)
(can't be done as long as the `expertsystem` only produces XML).
- [x] [Step 2: Generate data samples](https://compwa.github.io/usage/workflow/2_generate_data.html)
(existing notebook needs to be renamed into `2_generate_data`)
- [x] [Step 3: Perform fit](https://compwa.github.io/usage/workflow/3_perform_fit.html) -- see https://github.com/ComPWA/tensorwaves/issues/68

**Comment by redeboer** [comment]
Closed by #143
